registry: "public.ecr.aws/datadog"
datadog:
  apiKeyExistingSecret: "datadog-secret"
  site: "us5.datadoghq.com"
  tags:
    - "env:local"
  clusterName: datadog-sandbox
  processAgent:
    enabled: true
    processCollection: true
  orchestratorExplorer:
    enabled: true
  apm:
    portEnabled: true
clusterAgent:
  configd:
  env:
    - name: DD_KUBELET_TLS_VERIFY
      value: "false"
process_config:
  process_collection:
    enabled: true
