apiVersion: "datadoghq.com/v2alpha1"
kind: "DatadogAgent"
metadata:
  name: "datadog"
spec:
  global:
    clusterName: "datadog-sandbox"
    site: "us5.datadoghq.com"
    tags:
      - "env:dev"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
  features:
    logCollection:
      enabled: true
      containerCollectAll: true
    apm:
      enabled: true
      hostPortConfig:
        enabled: true
        hostPort: 8126 # default      
  override:
    nodeAgent:
      extraConfd:
        configDataMap:    
    clusterAgent:
      containers:
        cluster-agent:
          env:
